services:
  # Backend service
  - type: web
    name: tamid-blog-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://tamid-blog-frontend.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend service
  - type: static
    name: tamid-blog-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tamid-blog-backend.onrender.com
    autoDeploy: true 