services:
  # Backend service
  - type: web
    name: tamid-blog-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend  # Points to the backend directory containing package.json
    buildCommand: npm install  # Installs dependencies in backend directory
    startCommand: node src/app.js  # Starts the Node.js application
    dockerfilePath: null  # Explicitly specify no Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://tamid-blog-frontend.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend service
  - type: static
    name: tamid-blog-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend  # Points to the frontend directory containing package.json
    buildCommand: npm install && npm run build  # Installs dependencies and builds the React app
    staticPublishPath: build  # The directory containing the built static files
    dockerfilePath: null  # Explicitly specify no Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://tamid-blog-backend.onrender.com
    autoDeploy: true 